### ISSUE TITLE
buying arm region 

### ISSUE THREAD

**Issue by Digifan43** [nikosgram/gringotts#160]
**Describe the bug**
hello
i have problem concerning buying a region (using arm) with emerald (using gringotts) in inventory AND in vault chest.
vault chest is withdrawn but not the inventory and region is baught.
Doesn't seem have problem with emeralds in hand OR in vault chest.

**To Reproduce**
1 having emeralds in vault chest
2 having emeralds in inventory
3 buy a region

**Expected behavior**
both vault chest and inventory are withdrawn

**Screenshots**

**Desktop (please complete the following information):**
 - Server Type: paper 1.20.1-194
 - Server Version: 1.20.1
 - Gringotts Version: 2.12.5

**Additional context**
`ERROR]: Could not pass event PlayerInteractEvent to AdvancedRegionMarket v3.5.3
org.gestern.gringotts.GringottsException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
        at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:470) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.remove(GringottsAccount.java:304) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.remove(GringottsEco.java:659) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.api.impl.VaultConnector.withdrawPlayer(VaultConnector.java:131) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.api.impl.VaultConnector.withdrawPlayer(VaultConnector.java:127) ~[gringotts-2.12.5.jar:?]
        at net.alex9849.arm.regions.Region.buy(Region.java:621) ~[advancedregionmarket-3.5.3.jar:?]
        at net.alex9849.arm.regions.SellRegion.signClickAction(SellRegion.java:32) ~[advancedregionmarket-3.5.3.jar:?]
        at net.alex9849.arm.handler.listener.SignClickListener.handleSignCmd(SignClickListener.java:63) ~[advancedregionmarket-3.5.3.jar:?]
        at net.alex9849.arm.handler.listener.SignClickListener.interactEvent(SignClickListener.java:46) ~[advancedregionmarket-3.5.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor251.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-194]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-194]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-194]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:591) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2015) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-194]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-194]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096) ~[?:?]
        at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:468) ~[gringotts-2.12.5.jar:?]
        ... 34 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
        at org.gestern.gringotts.GringottsAccount.removeFromShulkerBox(GringottsAccount.java:332) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.lambda$remove$2(GringottsAccount.java:265) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.lambda$callSync$0(GringottsAccount.java:54) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.callSync(GringottsAccount.java:61) ~[gringotts-2.12.5.jar:?]`

**Comment by nikosgram** [comment]
Hello :) 

Is it possible to reproduce the issue with 2.12.5 version of Gringotts?

Download link: [https://github.com/nikosgram/gringotts/releases/download/2.12.5/gringotts-2.12.5.jar](https://github.com/nikosgram/gringotts/releases/download/2.12.5/gringotts-2.12.5.jar)

**Comment by Digifan43** [comment]
2.12.5 is the version installed
same issue with emeralds in inventory and nothing in vault chest, no withdrawn and region baught
no problem when no vault chest exist

**Comment by nikosgram** [comment]
Do you have Vault as part of your plugins?

**Comment by Digifan43** [comment]
yes
Vault v1.7.3-b131

**Comment by nikosgram** [comment]
## Duplicate triage

Closing as a duplicate of #170. Both reports provide the same null `ItemStack` / `removeFromShulkerBox` failure during a Vault-driven withdrawal, with partial money removal. #170 contains the broader reproducible multi-vault case and remains the canonical tracker.
