### ISSUE TITLE
NPE on withdraw from vault and enderchest

### ISSUE THREAD

**Issue by Shepelzz** [nikosgram/gringotts#170]
Got NPE while trying withdraw money from vault.

Precondition:
- Vault chest has 1002 
- Inventory 0
- Enderchest has 20
I`m using last 2.12.5 version

Steps to reproduce:
type /money withdraw 1022

Expected:
1022 will be transfered to inventory.

Actual:
All money in vault (1002) disappeared.
Nothing comes to inventory.

```
[09:29:32 INFO]: MorjTop1GG issued server command: /balance withdraw 1022
[09:29:32 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'balance' in plugin Gringotts v2.12.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:947) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2391) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2351) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1996]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.gestern.gringotts.GringottsException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
        at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:470) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.remove(GringottsAccount.java:304) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.api.impl.GringottsEco$ValidPlayerAccount.withdraw(GringottsEco.java:785) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.commands.GringottsAbstractExecutor.withdraw(GringottsAbstractExecutor.java:158) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.commands.MoneyExecutor.onCommand(MoneyExecutor.java:59) ~[gringotts-2.12.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096) ~[?:?]
        at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:468) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.remove(GringottsAccount.java:304) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.api.impl.GringottsEco$ValidPlayerAccount.withdraw(GringottsEco.java:785) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.commands.GringottsAbstractExecutor.withdraw(GringottsAbstractExecutor.java:158) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.commands.MoneyExecutor.onCommand(MoneyExecutor.java:59) ~[gringotts-2.12.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
        at org.gestern.gringotts.GringottsAccount.removeFromShulkerBox(GringottsAccount.java:332) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.lambda$remove$2(GringottsAccount.java:265) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.lambda$callSync$0(GringottsAccount.java:54) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.callSync(GringottsAccount.java:61) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.GringottsAccount.remove(GringottsAccount.java:304) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.api.impl.GringottsEco$ValidPlayerAccount.withdraw(GringottsEco.java:785) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.commands.GringottsAbstractExecutor.withdraw(GringottsAbstractExecutor.java:158) ~[gringotts-2.12.5.jar:?]
        at org.gestern.gringotts.commands.MoneyExecutor.onCommand(MoneyExecutor.java:59) ~[gringotts-2.12.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

**Comment by Shepelzz** [comment]
@nikosgram 
Can it be the place where null check is missed? I see fix on add method, but there is no check on remove...

![Снимок экрана 2024-02-09 214505](https://github.com/nikosgram/gringotts/assets/38551207/60b43ba1-ca7c-466f-9698-71f83f2ff8f6)

**Comment by Admyral** [comment]
This also happens when you have multiple vault chests and the withdrawal exceeds the amount that is in the first chest.

Steps to reproduce (using 2.12.5 version on paper-1.20.4-365):
First Vault Chest : put in (or use /m deposit) 1000 currency equivalent in items
Second Vault Chest :  put in (or use /m deposit) 1000 currency equivalent in items
/m withdraw 1001 (any amount exceeding the contents on the first chest

Expected Result:
1001 will be transferred to inventory.

Actual Result:
All items in the First Vault Chest have disappeared.
Nothing has changed in the Second Vault Chest.
Nothing comes to inventory.

I wanted try and dig into the code and try and fix this myself, but I need some Maven training. I can't even get it to compile.  :(

**Comment by Shepelzz** [comment]
> This also happens when you have multiple vault chests and the withdrawal exceeds the amount that is in the first chest.
> 
> Steps to reproduce (using 2.12.5 version on paper-1.20.4-365): First Vault Chest : put in (or use /m deposit) 1000 currency equivalent in items Second Vault Chest : put in (or use /m deposit) 1000 currency equivalent in items /m withdraw 1001 (any amount exceeding the contents on the first chest
> 
> Expected Result: 1001 will be transferred to inventory.
> 
> Actual Result: All items in the First Vault Chest have disappeared. Nothing has changed in the Second Vault Chest. Nothing comes to inventory.
> 
> I wanted try and dig into the code and try and fix this myself, but I need some Maven training. I can't even get it to compile. :(

As for me it was helpful just to restrict enderchest use as vault, together with restriction for users to create own vaults.
All vaults was created by responsible person on player request in the bank.
It helps to avoid this double vault problem.

BTW I didn't have any problems with the build... but I couldn't fix it too) need to debug and lookup deeper into logic

**Comment by Admyral** [comment]
> > This also happens when you have multiple vault chests and the withdrawal exceeds the amount that is in the first chest.
> > Steps to reproduce (using 2.12.5 version on paper-1.20.4-365): First Vault Chest : put in (or use /m deposit) 1000 currency equivalent in items Second Vault Chest : put in (or use /m deposit) 1000 currency equivalent in items /m withdraw 1001 (any amount exceeding the contents on the first chest
> > Expected Result: 1001 will be transferred to inventory.
> > Actual Result: All items in the First Vault Chest have disappeared. Nothing has changed in the Second Vault Chest. Nothing comes to inventory.
> > I wanted try and dig into the code and try and fix this myself, but I need some Maven training. I can't even get it to compile. :(
> 
> As for me it was helpful just to restrict enderchest use as vault, together with restriction for users to create own vaults. All vaults was created by responsible person on player request in the bank. It helps to avoid this double vault problem.
> 
> BTW I didn't have any problems with the build... but I couldn't fix it too) need to debug and lookup deeper into logic

I'm sure the build is fine... I just don't know how to do it.  :)

**Comment by weaves7** [comment]
Please try this test build https://github.com/weaves7/Gringotts/releases/tag/v.2.12.7-SNAPSHOT

**Comment by nikosgram** [comment]
## Canonical money-safety bug

This is the canonical tracker for the shulker-box null-pointer and partial-removal family (duplicates #166, #160, and #188). Commit `f7ade10` adds a null guard in `removeFromShulkerBox`, but this issue remains open because its multi-vault withdrawal scenario also requires verifying that a failed operation cannot remove value from only the first source.

Required future test matrix: inventory, ender chest, shulker boxes, and multiple vault chests; exact balance before/after on both success and failure.

**Comment by nikosgram** [comment]
## Started

I am starting a focused remediation for the canonical money-safety failure.

Plan:
- [ ] Reproduce the multi-vault withdrawal failure in an automated test.
- [ ] Ensure failed withdrawals do not mutate any source balance.
- [ ] Cover shulker-box null slots and the successful multi-source path.
- [ ] Run the full Maven test suite and document manual Paper verification.

Scope excludes unrelated Towny behavior and broader account-model changes.

**Comment by nikosgram** [comment]
## Resolution

The reported NPE path is fixed in the maintained code by commit `f7ade10`: `removeFromShulkerBox` now skips null inventory slots before reading `ItemStack` metadata.

Verification completed:
- `mvn -B test -q` — passed
- `mvn -B package -q` — passed
- Paper 1.21.6-48 with Gringotts 3.0.1-SNAPSHOT and Vault 1.7.3 — Gringotts loaded and Vault reported `Gringotts hooked`

Manual verification still recommended for the historical multi-vault scenario: place currency across two vault chests, withdraw an amount exceeding the first chest, and confirm the combined amount reaches the player with no source-value loss. This requires a connected player and is not executable from the server console alone.
