### ISSUE TITLE
Error in 1.20.4

### ISSUE THREAD

**Issue by Itras500** [nikosgram/gringotts#188]
I know that the plugin is only for 1.19, but by and large it also seems to work for 1.20.4. Except for one point. If I only have money in my inventory and not in the Vault, I can't buy anything in a QuickShop. I always get an error that it didn't work. The following message is displayed in the console. 

> [10:18:36] [Server thread/WARN]: [QuickShop] QuickShop received an error when processing Economy response, THIS NOT A QUICKSHOP FAULT, you might need ask help with your Economy Provider plugin (Gringotts) author.
org.gestern.gringotts.GringottsException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
	at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:470) ~[gringotts-2.12.5.jar:?]
	at org.gestern.gringotts.GringottsAccount.remove(GringottsAccount.java:304) ~[gringotts-2.12.5.jar:?]
	at org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.remove(GringottsEco.java:659) ~[gringotts-2.12.5.jar:?]
	at org.gestern.gringotts.api.impl.VaultConnector.withdrawPlayer(VaultConnector.java:131) ~[gringotts-2.12.5.jar:?]
	at org.gestern.gringotts.api.impl.VaultConnector.withdrawPlayer(VaultConnector.java:127) ~[gringotts-2.12.5.jar:?]
	at org.maxgamer.quickshop.economy.Economy_Vault.withdraw(Economy_Vault.java:232) ~[QuickShop-5.1.2.5.jar:?]
	at org.maxgamer.quickshop.economy.Economy_Vault.withdraw(Economy_Vault.java:220) ~[QuickShop-5.1.2.5.jar:?]
	at org.maxgamer.quickshop.api.economy.EconomyTransaction.commit(EconomyTransaction.java:178) ~[QuickShop-5.1.2.5.jar:?]
	at org.maxgamer.quickshop.api.economy.EconomyTransaction.commit(EconomyTransaction.java:142) ~[QuickShop-5.1.2.5.jar:?]
	at org.maxgamer.quickshop.api.economy.EconomyTransaction.failSafeCommit(EconomyTransaction.java:129) ~[QuickShop-5.1.2.5.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.actionSell(SimpleShopManager.java:1134) ~[QuickShop-5.1.2.5.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.actionTrade(SimpleShopManager.java:1515) ~[QuickShop-5.1.2.5.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.lambda$handleChat$4(SimpleShopManager.java:558) ~[QuickShop-5.1.2.5.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096) ~[?:?]
	at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:468) ~[gringotts-2.12.5.jar:?]
	... 20 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "itemStack" is null
	at org.gestern.gringotts.GringottsAccount.removeFromShulkerBox(GringottsAccount.java:332) ~[gringotts-2.12.5.jar:?]
	at org.gestern.gringotts.GringottsAccount.lambda$remove$2(GringottsAccount.java:265) ~[gringotts-2.12.5.jar:?]
	at org.gestern.gringotts.GringottsAccount.lambda$callSync$0(GringottsAccount.java:54) ~[gringotts-2.12.5.jar:?]
	at org.gestern.gringotts.GringottsAccount.callSync(GringottsAccount.java:61) ~[gringotts-2.12.5.jar:?]
	... 20 more

 - Server Type: Paper
 - Server Version: 1.20.4
 - Gringotts Version: 2.12.5

Usingen QuickShop as ShopPlugin and Vault.

**Comment by Relaxing9** [comment]
I think that was fixed here: https://github.com/nikosgram/gringotts/releases/tag/2.12.6-SNAPSHOT

**Comment by Itras500** [comment]
With this version, others errors comes up. 
If I execute /money the sign of my Vault is dropped and the vault destroyed. 
`[10:51:02] [Server thread/INFO]: Itras issued server command: /money
[10:51:02] [Server thread/INFO]: [Gringotts] Destroying orphaned vault: [vault] 28, 72, -572, CraftWorld{name=Westwindinseln}`

And if I buy something at a QuickShop the vault of the seller is also destroyed and I cant buy anything. 

`[10:53:02] [Server thread/INFO]: [Gringotts] Destroying orphaned vault: [vault] -290, 81, -412, CraftWorld{name=Westwindinseln}
[10:53:02] [Server thread/ERROR]: [QuickShop] EconomyTransaction Failed, last error:Failed to deposit 5.0 to player 5c57ce2d-92d0-4ae7-b434-8cd23c1bb518 account. LastError: Gringotts: FAILURE - Nicht genug Platz.`

**Comment by Itras500** [comment]
Ah closed it by accident

**Comment by nikosgram** [comment]
## Duplicate triage

Closing as a duplicate of #170. Both reports trace the monetary operation to a null `ItemStack` while removing funds and describe a failed transaction. #170 is the canonical report because it also records the multi-vault withdrawal/data-loss scenario.

Current history note: commit `f7ade10` adds the null guard in `removeFromShulkerBox`; revalidation of the broader transaction behavior remains tracked on #170.
