### ISSUE TITLE
Gringotts 2.11.1-SNAPSHOT & QuickShop Reremake | 1.15 3.1.3.14 communication issue

### ISSUE THREAD

**Issue by Blazio73** [nikosgram/gringotts#29]
Been using Gringotts for a while along with Vault & EssentialsX.  Had to find a new shop plugin and cam across QuickShop.
After setting up a shop and try to sell an item, the following message come across on the backend:

[15:43:33] [Server thread/WARN]: java.lang.NoSuchFieldError: accountHolderFactory
[15:43:33] [Server thread/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_Gringotts.getBalance(Economy_Gringotts.java:136)
[15:43:33] [Server thread/WARN]: 	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20)
[15:43:33] [Server thread/WARN]: 	at org.maxgamer.quickshop.Economy.Economy_Vault.getBalance(Economy_Vault.java:241)
[15:43:33] [Server thread/WARN]: 	at org.maxgamer.quickshop.Economy.Economy.getBalance(Economy.java:85)
[15:43:33] [Server thread/WARN]: 	at org.maxgamer.quickshop.Listeners.PlayerListener.onClick(PlayerListener.java:177)
[15:43:33] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
[15:43:33] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:43:33] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:43:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[15:43:33] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:43:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[15:43:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[15:43:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:442)
[15:43:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:409)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:137)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1197)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
[15:43:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827)
[15:43:33] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:43:33] [Server thread/WARN]: This seems not QuickShop fault, you should contact with your economy plugin author. (Gringotts)[m

Any ideas

**Comment by nikosgram** [comment]
Hello @Blazio73,

Can you test this on the latest snapshot version of Gringotts?

https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-ref98c00

Please remember, do not use this version in your server, might cause issues.

Thank you.
