### ISSUE TITLE
2.11.2-SNAPSHOT - won't load with Paper-133

### ISSUE THREAD

**Issue by Kwikxilver** [nikosgram/gringotts#32]
Having an issue with the latest snapshot - it won't load in Paper 133. let me know if you need any more details!

[22:40:18] [Server thread/ERROR]: Could not load 'plugins/Gringotts-2.11.2-SNAPSHOT-rf40b38b.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: awareness has wrong type
	at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile.java:1038) ~[patched_1.15.2.jar:git-Paper-133]
	at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:240) ~[patched_1.15.2.jar:git-Paper-133]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:164) ~[patched_1.15.2.jar:git-Paper-133]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:147) ~[patched_1.15.2.jar:git-Paper-133]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-133]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.bukkit.plugin.PluginAwareness
	at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile.java:1035) ~[patched_1.15.2.jar:git-Paper-133]
	... 7 more

**Comment by nikosgram** [comment]
Hello @yntel , which build version is that? f40b38b or 4d100bc

**Comment by Kwikxilver** [comment]
Hi @nikosgram , I'm using f40b38b

**Comment by nikosgram** [comment]
Try this version: https://github.com/nikosgram/Gringotts/releases/tag/2.11.2-SNAPSHOT-r4d100bc

4d100bc

**Comment by Kwikxilver** [comment]
@nikosgram thank you! This version loads and seems to work fine. I will continue testing and try and find some bugs. Appreciate it!
