### ISSUE TITLE
Vault sign not working

### ISSUE THREAD

**Issue by PenteractAI** [nikosgram/gringotts#41]
Hello, i've tried to create an [vault] sign but it give me an error. I've tried with versions 2.9 to 2.11.2-SNAPSHOT-rf77e523.

`[15:23:17 ERROR]: Could not pass event SignChangeEvent to Gringotts v2.11.1-SNAPSHOT
 java.lang.NoSuchMethodError: org.bukkit.block.Block.getBlockData()Lorg/bukkit/block/data/BlockData;
at org.gestern.gringotts.Util.chestBlock(Util.java:99) ~[?:?]
at org.gestern.gringotts.event.AccountListener.onSignChange(AccountListener.java:58) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:11643ae]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:11643ae]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:11643ae]
at net.minecraft.network.NetHandlerPlayServer.func_147343_a(NetHandlerPlayServer.java:2375) [pa.class:?]
at net.minecraft.network.play.client.CPacketUpdateSign.func_148833_a(SourceFile:44) [lx.class:?]
at net.minecraft.network.play.client.CPacketUpdateSign.func_148833_a(SourceFile:10) [lx.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:466) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

I've seen that it's an old issue but i haven't find a solution...

**Comment by nikosgram** [comment]
Hello, what's your bucket version? :)

**Comment by PenteractAI** [comment]
I'm using bukkit 1.12.2 and i've tried with Vault 1.5.6 and 1.7.2. The only version that is "working" is Vault 1.5.6 and Gringotts 2.10 but only chests can be used as vault (not enderchest, etc). ^^
