### ISSUE TITLE
Get Gringotts balances too slow

### ISSUE THREAD

**Issue by ghost** [nikosgram/gringotts#46]
In Dynmap towny it updates the balances of all towny towns, and nations, however it gringotts ends up timing out and spam exceptions:
```
org.gestern.gringotts.GringottsException: java.util.concurrent.TimeoutException
	at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:298) ~[?:?]
	at org.gestern.gringotts.GringottsAccount.getBalance(GringottsAccount.java:80) ~[?:?]
	at org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.balance(GringottsEco.java:490) ~[?:?]
	at org.gestern.gringotts.api.impl.VaultConnector.getBalance(VaultConnector.java:76) ~[?:?]
	at com.palmergames.bukkit.towny.TownyEconomyHandler.getBalance(TownyEconomyHandler.java:260) ~[?:?]
	at com.palmergames.bukkit.towny.object.EconomyAccount.getHoldingBalance(EconomyAccount.java:174) ~[?:?]
	at com.palmergames.bukkit.towny.object.EconomyAccount.getHoldingFormattedBalance(EconomyAccount.java:199) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin.formatInfoWindow(DynmapTownyPlugin.java:462) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin.handleTown(DynmapTownyPlugin.java:584) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin.updateTowns(DynmapTownyPlugin.java:808) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin.access$000(DynmapTownyPlugin.java:52) ~[?:?]
	at org.dynmap.towny.DynmapTownyPlugin$TownyUpdate.run(DynmapTownyPlugin.java:300) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-212]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-212]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[?:1.8.0_242]
	at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:296) ~[?:?]
```

**Comment by ghost** [comment]
Ignore this

**Comment by darkchroma** [comment]
Could you please shed some light on how you fixed this? I'm also have the same problems on my 1.16 paper spigot java server
