### ISSUE TITLE
Console spam with placeholderAPI issue with gringotts. paper spigot 1.16

### ISSUE THREAD

**Issue by darkchroma** [nikosgram/gringotts#58]
>.... [07:05:02 WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.6 generated an exception while executing task 3671
org.gestern.gringotts.GringottsException: java.util.concurrent.TimeoutException
at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:298) ~[?:?]
at org.gestern.gringotts.GringottsAccount.getBalance(GringottsAccount.java:80) ~[?:?]
at org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.balance(GringottsEco.java:473) ~[?:?]
at org.gestern.gringotts.api.impl.VaultConnector.getBalance(VaultConnector.java:81) ~[?:?]
at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220) ~[?:?]
at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-86]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-86]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.concurrent.TimeoutException
at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886) ~[?:?]
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021) ~[?:?]
at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:296) ~[?:?]
... 11 more

**Comment by Kooramah** [comment]
getting the same error

**Comment by nikosgram** [comment]
Too old
